"""Deprecated alias for :mod:`strands.bidi.types`."""

from typing import Any

from strands.bidi import types as _real
from strands.bidi.types import (
    AudioChannel,
    AudioDelta,
    AudioFormat,
    BidiAgentInput,
    BidiAudioDeltaEvent,
    BidiAudioStartEvent,
    BidiAudioStopEvent,
    BidiBargeInEvent,
    BidiConnectionRestartEvent,
    BidiConnectionStartEvent,
    BidiConnectionStopEvent,
    BidiConnectionWarningEvent,
    BidiContentBlock,
    BidiContentBlockData,
    BidiContentDelta,
    BidiContentDeltaData,
    BidiContentMetadata,
    BidiMessage,
    BidiOutputEvent,
    BidiReasoningBlockEvent,
    BidiReasoningDeltaEvent,
    BidiReasoningStartEvent,
    BidiReasoningStopEvent,
    BidiResponseStartEvent,
    BidiResponseStopEvent,
    BidiTextBlockEvent,
    BidiTextDeltaEvent,
    BidiTextStartEvent,
    BidiTextStopEvent,
    BidiToolUseBlocksEvent,
    BidiTranscriptBlockEvent,
    BidiTranscriptDeltaEvent,
    BidiTranscriptStartEvent,
    BidiTranscriptStopEvent,
    BidiUsageEvent,
    BidiUserContentBlock,
    BidiUserContentBlockData,
    InputStream,
    OutputStream,
    Role,
    TokenDetails,
)

__all__ = [
    "AudioChannel",
    "AudioDelta",
    "AudioFormat",
    "BidiAgentInput",
    "BidiAudioDeltaEvent",
    "BidiAudioStartEvent",
    "BidiAudioStopEvent",
    "BidiContentBlock",
    "BidiContentBlockData",
    "BidiContentDelta",
    "BidiContentDeltaData",
    "BidiContentMetadata",
    "BidiConnectionRestartEvent",
    "BidiConnectionStartEvent",
    "BidiConnectionStopEvent",
    "BidiConnectionWarningEvent",
    "BidiMessage",
    "BidiOutputEvent",
    "BidiReasoningBlockEvent",
    "BidiReasoningDeltaEvent",
    "BidiReasoningStartEvent",
    "BidiReasoningStopEvent",
    "BidiBargeInEvent",
    "BidiResponseStartEvent",
    "BidiResponseStopEvent",
    "BidiToolUseBlocksEvent",
    "BidiTextBlockEvent",
    "BidiTextDeltaEvent",
    "BidiTextStartEvent",
    "BidiTextStopEvent",
    "BidiTranscriptDeltaEvent",
    "BidiTranscriptStartEvent",
    "BidiTranscriptStopEvent",
    "BidiTranscriptBlockEvent",
    "BidiUsageEvent",
    "BidiUserContentBlock",
    "BidiUserContentBlockData",
    "InputStream",
    "OutputStream",
    "Role",
    "TokenDetails",
]


def __getattr__(name: str) -> Any:
    """Forward attribute access to :mod:`strands.bidi.types`."""
    return getattr(_real, name)
